#!/usr/bin/env python
import argparse

import async_http_load_tester


def _url(url):
    """
    Handles validation for argparse URL strings
    """
    if not url.startswith('http://'):
        raise argparse.ArgumentTypeError("URL must begin with http://")
    return url
parser = argparse.ArgumentParser()
parser.add_argument('site_to_test', type=_url, help='URL of site to test, starting with http://')
parser.add_argument('--max-simultaneous', '-m', type=int, default=50, dest='max_simultaneous')
parser.add_argument('--step', '-s', type=int, default=10, dest='step')
args = parser.parse_args()
results = async_http_load_tester.perform_load_test(args.site_to_test, args.max_simultaneous,
                                                   args.step)
print("Final Results: {0}".format(results))
