#!/usr/bin/env python
import argparse

import async_http_load_tester


def _url(url):
    """
    Handles validation for argparse URL strings
    """
    if not url.startswith('http://'):
        raise argparse.ArgumentTypeError("URL must begin with http://")
    return url
parser = argparse.ArgumentParser()
parser.add_argument('site_to_test', type=_url, help='URL of site to test, starting with http://')
args = parser.parse_args()
results = async_http_load_tester.perform_load_test(args.site_to_test)
print("Final Results: {0}".format(results))
